interface Env{OPENAI_API_KEY:string;ALLOWED_ORIGIN?:string;COUNCIL_MODEL_FAST?:string;COUNCIL_MODEL_JUDGE?:string;COUNCIL_VECTOR_STORE_ID?:string;DB?:any}
type F='thread'|'panel'|'council'|'claims'|'brainstorm';type D='general'|'watch'|'business';type B='quick'|'standard'|'deep';type E='none'|'project'|'web'|'project-web'|'deep-web';
type R={id:string;name:string;role:string;bias:string;objective:string;evidence:string;failure:string;revise:string;abstain:string};type P={resident:string;phase:string;text:string;confidence:number;pre?:number;post?:number;target?:string;cont?:boolean;citations?:any[]};
type Req={title:string;body:string;format?:F;domain?:D;tone?:string;budget?:B;evidence?:E;panelSize?:number;mode?:string;engine?:string;useWeb?:boolean};
export const FORMAT_MENU=['1. 「2ch民で焼いて」→ スレ表示。煽り・反論・レスバ込みで論点を削る','2. 「みんなで議論して」→ ひな壇。複数視点をテンポよくぶつける','3. 「冷静に決めて」→ 評議会。選択肢を比較して最終判断まで出す','4. 「監査して」→ Claim Board。主張・根拠・反証・未確認を分解する','5. 「案出して」→ Brainstorming Board。独立発想→整理→発展→絞り込み'];
const r=(id:string,name:string,role:string,bias:string,objective:string,evidence:string,failure:string,revise:string,abstain:string):R=>({id,name,role,bias,objective,evidence,failure,revise,abstain});
const PEOPLE:R[]=[r('source','史料警察','一次資料・文献・推論を分離','断定に厳しい','根拠強度を最大化','一次>同時代>専門>二次>推論','保留しすぎる','直接資料で修正','根拠不明なら保留'),r('mechanic','機構オタク','構造・操作・故障','機構偏重','構造差と因果を具体化','実機・分解図・特許','珍しさを価値化','実機衝突で撤回','資料なしは断定しない'),r('market','市場屋','価格・流動性','値札偏重','市場現実化','成約・出現頻度','浪漫を価格化','成約分布で修正','薄い市場は幅'),r('historian','時計史厨','前後関係・同時代比較','歴史偏重','系譜を正しく置く','同時代資料・特許','物語化','先行例で修正','系譜不明を残す'),r('collector','沼の住人','所有・実機経験','欲望偏重','実機の違和感を拾う','一次観察を一般化しない','好き=重要','個体差で撤回','未体験を演じない'),r('editor','編集者','伝達と断定リスク','物語偏重','正確に伝える','事実/推論/比喩を分離','削りすぎる','意味変化は撤回','確度不明を強調しない'),r('devil','前提破壊班','前提・反証条件','否定偏重','隠れ前提を壊す','反例・別説明','壊しすぎる','耐えた主張は認める','逆張りだけしない'),r('cfo','冷徹なCFO','費用対効果','浪漫軽視','判断価値/コストを見る','追加調査の情報価値','長期価値を軽視','低コスト高影響なら投資','本人の価値判断は返す'),r('novice','初見の名無しさん','初見理解','専門性不足','前提なしで通るか','比較・因果','削りすぎる','必要語は説明付きで受容','専門判断は譲る'),r('researcher','検索沼研究員','検索拡張・反証','調査過多','検索漏れを減らす','原ページまで到達','止まれない','期待値低下で停止','原典未到達は未確認'),r('minimal','ミニマリスト','必要性','削りすぎる','複雑性を削る','目的直結度','安全策も削る','再発増なら残す','証拠性は削らない'),r('wild','野良の変人','異分野接続','再現性低い','枠外案を出す','発想と事実を分離','使えない案量産','条件不適合なら撤回','比喩を事実にしない'),r('aa','AA職人','空気を切る','進まない','threadの温度','証拠判断不参加','議論停止','重要局面で黙る','thread以外不参加')];
const C:Record<F,{label:string,size:number,prefix:string}>={thread:{label:'2chスレ',size:6,prefix:'C'},panel:{label:'ひな壇',size:7,prefix:'T'},council:{label:'評議会',size:6,prefix:'O'},claims:{label:'Claim Board',size:6,prefix:'C'},brainstorm:{label:'Brainstorming Board',size:8,prefix:'I'}};
const H=(o:string)=>({'content-type':'application/json; charset=utf-8','access-control-allow-origin':o,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type','cache-control':'no-store'}),O=(e:Env)=>e.ALLOWED_ORIGIN||'*';
const clean=(s:string)=>s.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');
function out(x:any){if(typeof x?.output_text==='string')return x.output_text.trim();return(x?.output||[]).flatMap((i:any)=>i?.type==='message'?(i.content||[]).filter((c:any)=>c.type==='output_text').map((c:any)=>c.text):[]).join('\n').trim()}
function meta(s:string){return{confidence:Math.max(0,Math.min(100,Number(s.match(/CONFIDENCE\s*[:：]\s*(\d+)/i)?.[1]||65))),target:s.match(/TARGET\s*[:：]\s*([^\n]+)/i)?.[1]?.trim(),cont:/CONTINUE\s*[:：]\s*YES/i.test(s),changed:/CHANGED\s*[:：]\s*YES/i.test(s),text:s.replace(/^\s*(?:CONFIDENCE|TARGET|STANCE|CONTINUE|CHANGED|CHOICE)\s*[:：].*$/gim,'').trim()}}
async function call(e:Env,prompt:string,tools:any[]=[],judge=false){const x=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${e.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:judge?(e.COUNCIL_MODEL_JUDGE||'gpt-5.6-terra'):(e.COUNCIL_MODEL_FAST||'gpt-5.6-luna'),input:prompt,tools,reasoning:{effort:judge?'high':'medium'},max_output_tokens:2800})});if(!x.ok)throw Error(`OpenAI ${x.status}: ${await x.text()}`);return x.json()}
function toolset(q:any,e:Env){const t:any[]=[];if(['web','project-web','deep-web'].includes(q.evidence))t.push({type:'web_search',search_context_size:q.evidence==='deep-web'?'high':'medium'});if(['project','project-web','deep-web'].includes(q.evidence)&&e.COUNCIL_VECTOR_STORE_ID)t.push({type:'file_search',vector_store_ids:[e.COUNCIL_VECTOR_STORE_ID],max_num_results:18});return t}
function pick(f:F,d:D,n:number){const core=d==='watch'?['source','mechanic','historian','editor','devil']:d==='business'?['cfo','editor','devil','novice','minimal']:f==='brainstorm'?['wild','editor','novice','devil','minimal']:f==='claims'?['source','devil','editor','researcher','minimal']:['editor','devil','novice','wild','minimal'];let rest=PEOPLE.map(x=>x.id).filter(x=>!core.includes(x)&&x!=='aa');if(f==='thread')rest.push('aa');return[...new Set([...core,...rest])].slice(0,n).map(id=>PEOPLE.find(x=>x.id===id)!).filter(Boolean)}
function norm(a:Req){const f=(a.format||(a.mode==='roast'?'thread':'panel')) as F,d=(a.domain||(a.mode==='watch'?'watch':a.mode==='business'?'business':'general')) as D,b=(a.budget||(a.engine==='quick'?'quick':a.engine==='deep-web-10'?'deep':'standard')) as B,ev=(a.evidence||(a.engine==='deep-web-10'?'deep-web':a.useWeb?'project-web':'project')) as E,n=Math.max(4,Math.min(10,Number(a.panelSize||C[f].size+(b==='deep'?1:0))));return{title:String(a.title||'').trim(),body:String(a.body||'').trim(),format:f,domain:d,budget:b,evidence:ev,residents:pick(f,d,n)}}
const prof=(x:R)=>`役割:${x.role} / 目的:${x.objective} / 証拠:${x.evidence} / 弱点:${x.failure} / 修正:${x.revise} / 棄権:${x.abstain}`;
async function first(q:any,e:Env){const t=toolset(q,e);return Promise.all(q.residents.map(async(x:R)=>{const y=await call(e,`あなたは${x.name}。${prof(x)}\n議題:${q.title}\n背景:${q.body}\n形式:${C[q.format as F].label}\n他住民を見ず独立に考える。事実と推論を分離し反証条件を1つ。架空の人口属性を演じない。200〜550字。最後に CONFIDENCE:0-100。`,t),m=meta(out(y));return{resident:x.id,phase:'silent',text:m.text,confidence:m.confidence} as P}))}
async function board(q:any,e:Env,p:P[]){const x=await call(e,`書記。人物ではなく主張/案単位へ整理。議題:${q.title}\n形式:${q.format}\n${p.map((z,i)=>`P${i+1}:${z.text}`).join('\n')}\n重複統合し対立を残す。${q.format==='claims'?'support/challenge/unknowns厳密。':q.format==='brainstorm'?'異質案を早く潰さない。':''}JSONのみ:{"label":"","items":[{"id":"${C[q.format as F].prefix}1","title":"","statement":"","support":[],"challenge":[],"unknowns":[]}],"tensions":[],"hotSeatId":null}`,[],true);try{return JSON.parse(clean(out(x)))}catch{return{label:C[q.format as F].label,items:p.slice(0,8).map((z,i)=>({id:`${C[q.format as F].prefix}${i+1}`,title:`論点${i+1}`,statement:z.text.slice(0,180)})),tensions:[]}}}
async function cross(q:any,e:Env,x:R,b:any,pre:number){const t=toolset(q,e),y=await call(e,`あなたは${x.name}。${prof(x)}\nBOARD:${b.items.map((i:any)=>`${i.id}:${i.statement}`).join('\n')}\n人でなく検証価値の高い項目1つを攻撃/補強/統合。同じ言い換え禁止。${q.format==='brainstorm'?'改造案も出す。':''}最後に TARGET:<ID> CONTINUE:YES|NO CONFIDENCE:0-100`,t),m=meta(out(y));return{resident:x.id,phase:'cross',text:m.text,confidence:m.confidence,pre,target:m.target,cont:m.cont} as P}
async function hot(q:any,e:Env,x:R,b:any,p:P[]){const focus=b.hotSeatId||p.find(z=>z.target)?.target||b.items[0]?.id,t=toolset(q,e),y=await call(e,`HOT SEAT:${focus}\nBOARD:${b.items.map((i:any)=>`${i.id}:${i.statement}`).join('\n')}\nあなたは${x.name}。既出反復なし。最強の反例か壊れない修正を1つ。最後に TARGET:${focus} CONTINUE:YES|NO CONFIDENCE:0-100`,t),m=meta(out(y));return{resident:x.id,phase:'hot-seat',text:m.text,confidence:m.confidence,target:focus,cont:m.cont} as P}
async function vote(q:any,e:Env,x:R,b:any,pre:number,p:P[]){const y=await call(e,`匿名再評価。${x.name}。初期確信:${pre}\nBOARD:${b.items.map((i:any)=>`${i.id}:${i.statement}`).join('\n')}\n反証:${p.filter(z=>z.phase!=='silent').map(z=>`${z.target}:${z.text}`).join('\n')}\n他人の投票を見ない。支持IDかABSTAIN、最大の不確実性。最後に CHOICE:<ID|ABSTAIN> CHANGED:YES|NO CONFIDENCE:0-100`),raw=out(y),m=meta(raw);return{resident:x.id,phase:'revote',text:m.text,confidence:m.confidence,pre,post:m.confidence,target:raw.match(/CHOICE\s*[:：]\s*([^\n]+)/i)?.[1]?.trim()} as P}
async function judge(q:any,e:Env,b:any,p:P[]){const y=await call(e,`議長。多数決だけで丸めず根拠・反証・匿名再評価・少数意見を比較。議題:${q.title}\nBOARD:${JSON.stringify(b)}\n議論:${p.map(z=>`${z.phase}/${z.target||''}:${z.text}`).join('\n')}\n条件付き結論可。少数派の強い反論を残す。JSONのみ:{"conclusion":"","recommended":"","consensus":[],"minorityReport":[],"unknowns":[],"nextEvidence":[]}`,[],true);try{return JSON.parse(clean(out(y)))}catch{return{conclusion:'裁定の構造化に失敗。各意見参照。',recommended:'',consensus:[],minorityReport:[],unknowns:[],nextEvidence:[]}}}
async function save(e:Env,x:any){if(!e.DB)return null;const id=crypto.randomUUID().replace(/-/g,'').slice(0,12);await e.DB.prepare('INSERT INTO threads (id,payload,created_at) VALUES (?,?,?)').bind(id,JSON.stringify(x),new Date().toISOString()).run();return id}
async function run(a:Req,e:Env){const q=norm(a);if(!q.title||!q.body)throw Error('title and body are required');const a1=await first(q,e),b=await board(q,e,a1),pre=new Map(a1.map(z=>[z.resident,z.confidence])),a2=await Promise.all(q.residents.filter((x:R)=>x.id!=='aa').map((x:R)=>cross(q,e,x,b,pre.get(x.id)||65)));let a3:P[]=[],stop='cross-examで情報利得が収束';if(a2.filter(z=>z.cont).length>=2&&new Set(a2.map(z=>z.target).filter(Boolean)).size>=2){a3=await Promise.all(q.residents.filter((x:R)=>x.id!=='aa').slice(0,q.budget==='deep'?5:3).map((x:R)=>hot(q,e,x,b,a2)));stop='最大1回のadaptive hot-seat後に停止'}const discussion=[...a1,...a2,...a3],a4=await Promise.all(q.residents.filter((x:R)=>x.id!=='aa').map((x:R)=>vote(q,e,x,b,pre.get(x.id)||65,discussion))),s=await judge(q,e,b,[...discussion,...a4]),result={version:'council-v2',title:q.title,body:q.body,format:q.format,formatLabel:C[q.format as F].label,domain:q.domain,budget:q.budget,evidence:q.evidence,panelSize:q.residents.length,protocol:['silent-position','board-synthesis','cross-exam','adaptive-hot-seat','private-revote','minority-report','chair'],board:b,posts:[...discussion,...a4],synthesis:s,stopReason:stop,createdAt:new Date().toISOString()};return{...result,shareId:await save(e,result)}}
function name(id:string){return PEOPLE.find(x=>x.id===id)?.name||id}function format(x:any){const s=x.synthesis;if(x.format==='claims')return`## Claim Board\n${x.board.items.map((i:any)=>`### ${i.id} ${i.title}\n${i.statement}\n- 支持:${(i.support||[]).join(' / ')||'なし'}\n- 反証:${(i.challenge||[]).join(' / ')||'なし'}\n- 未確認:${(i.unknowns||[]).join(' / ')||'なし'}`).join('\n\n')}\n\n## 監査結論\n${s.conclusion}`;if(x.format==='brainstorm')return`## Brainstorming Board\n${x.board.items.map((i:any)=>`- **${i.id} ${i.title}** — ${i.statement}`).join('\n')}\n\n## 絞り込み\n${s.conclusion}\n${s.recommended?`推奨:${s.recommended}`:''}`;if(x.format==='council')return`## 評議会決定\n${s.conclusion}\n${s.recommended?`推奨:${s.recommended}\n`:''}\n## Minority Report\n${(s.minorityReport||[]).map((z:string)=>`- ${z}`).join('\n')||'- なし'}\n\n## 未確認\n${(s.unknowns||[]).map((z:string)=>`- ${z}`).join('\n')||'- なし'}`;if(x.format==='panel')return x.posts.filter((z:P)=>z.phase==='silent'||z.phase==='cross').map((z:P)=>`**${name(z.resident)}** ${z.text}`).join('\n\n')+`\n\n## 司会まとめ\n${s.conclusion}`;let n=1;return x.posts.filter((z:P)=>z.phase!=='revote').map((z:P)=>`${n++} 名前:${name(z.resident)}${z.target?` >>${z.target}`:''}\n${z.text}`).join('\n\n')+`\n\n${n} 名前:名無しさん＠議長\n${s.conclusion}`}
const MCP={name:'run_council',description:`COUNCIL V2. ユーザーが「焼いて」だけなら実行せず、必ず先にこの5択をそのまま提示:${FORMAT_MENU.join(' / ')}。選択後は会話・資料・Project・GitHubの既知情報を再利用し、精度を実質的に上げる不足情報だけ質問する。`,inputSchema:{type:'object',properties:{title:{type:'string'},body:{type:'string'},format:{type:'string',enum:['thread','panel','council','claims','brainstorm']},domain:{type:'string',enum:['general','watch','business']},budget:{type:'string',enum:['quick','standard','deep']},evidence:{type:'string',enum:['none','project','web','project-web','deep-web']},panelSize:{type:'integer',minimum:4,maximum:10}},required:['title','body','format'],additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:false,openWorldHint:true}};
const MH=(e:Env)=>({...H(O(e)),'access-control-allow-headers':'content-type,authorization,mcp-protocol-version,mcp-session-id'}),MR=(id:any,result:any,e:Env)=>new Response(JSON.stringify({jsonrpc:'2.0',id,result}),{headers:MH(e)});async function mcp(req:Request,e:Env){if(req.method==='OPTIONS')return new Response(null,{status:204,headers:MH(e)});if(req.method!=='POST')return new Response(null,{status:405,headers:MH(e)});let m:any;try{m=await req.json()}catch{return MR(null,{error:'Parse error'},e)}if(m?.id==null)return new Response(null,{status:202,headers:MH(e)});if(m.method==='initialize')return MR(m.id,{protocolVersion:'2025-06-18',capabilities:{tools:{listChanged:false}},serverInfo:{name:'VINTAGE ALARM Council',version:'2.0.0'},instructions:'Plain 焼いて = router. Show exact 5 choices before run_council. Reuse known context; clarify only when material.'},e);if(m.method==='ping')return MR(m.id,{},e);if(m.method==='tools/list')return MR(m.id,{tools:[MCP]},e);if(m.method==='tools/call'&&m.params?.name==='run_council'){try{const x=await run(m.params?.arguments||{},e);return MR(m.id,{content:[{type:'text',text:`COUNCIL V2\nFORMAT:${x.formatLabel}\nSTOP:${x.stopReason}\n\n${format(x)}`}],isError:false},e)}catch(z:any){return MR(m.id,{content:[{type:'text',text:'Council failed: '+(z?.message||String(z))}],isError:true},e)}}return MR(m.id,{error:'Method not found'},e)}
export default{async fetch(req:Request,e:Env){const u=new URL(req.url),h=H(O(e));if(u.pathname==='/mcp')return mcp(req,e);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:h});if(req.method==='GET'&&u.pathname==='/health')return new Response(JSON.stringify({ok:true,version:'council-v2',openai:!!e.OPENAI_API_KEY,vectorStore:!!e.COUNCIL_VECTOR_STORE_ID,db:!!e.DB}),{headers:h});if(req.method==='GET'&&u.pathname==='/api/menu')return new Response(JSON.stringify({version:'council-v2',menu:FORMAT_MENU}),{headers:h});if(req.method==='GET'&&u.pathname.startsWith('/api/thread/')){if(!e.DB)return new Response(JSON.stringify({error:'DB not configured'}),{status:501,headers:h});const row=await e.DB.prepare('SELECT payload FROM threads WHERE id=?').bind(u.pathname.split('/').pop()).first();return row?new Response(row.payload,{headers:h}):new Response(JSON.stringify({error:'not found'}),{status:404,headers:h})}if(req.method==='POST'&&u.pathname==='/api/council'){try{return new Response(JSON.stringify(await run(await req.json() as Req,e)),{headers:h})}catch(z:any){return new Response(JSON.stringify({error:z?.message||String(z)}),{status:500,headers:h})}}return new Response(JSON.stringify({error:'not found'}),{status:404,headers:h})}}
